version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge