version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: mcp_db
      POSTGRES_USER: mcpuser
      POSTGRES_PASSWORD: mcppassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  mcp-client:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mcp-client.rule=Host(`mcp.nandus.com.br`)"
      - "traefik.http.services.mcp-client.loadbalancer.server.port=8000"
    depends_on:
      - postgres
      - traefik

  mcp-server:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mcp-server.rule=Host(`mcp-server.nandus.com.br`)"
      - "traefik.http.services.mcp-server.loadbalancer.server.port=8001"
    depends_on:
      - postgres
      - traefik

volumes:
  postgres-data: